models:
  roi_model_path: "C:/Users/mzinn1/Desktop/gcamp_model/roi_classifier_20260122_142743.joblib"
  roi_config_path: "roi_classifier/models/roi_classifier_config.json"
  spike_model_path: "C:/Users/mzinn1/Desktop/gcamp_model/spike_classifier_20260122_163505.joblib"
  spike_config_path: "spike_classifier/models/spike_classifier_config.json"
  cascade_model_name: "Global_EXC_30Hz_smoothing100ms_high_noise"
  cascade_model_dir: "Cascade/Pretrained_models"

cascade_batch_size: 64

traces:
  sensor_type: "gcamp8s"   # gcamp8s, gcamp6f, or generic (affects smoothing window)
  smooth_sigma: 4.0        # Gaussian smoothing sigma

roi_filtering:
  normalization: "minmax"  # Normalization strategy: "minmax" or "deltaf"

spike_detection:
  prob_sigma: 4.0          # Gaussian smoothing
  window_size: 5           # +/- frames for F peak search
  min_prominence: 0.05     # Min cascade prominence
  min_distance: 8          # Min frames between spikes
  edge_trim: 32           # Ignore edge spikes

grouping:
  sttc:
    time_window: .4       # 33ms, 50ms, 100ms, 200ms, 300ms
    correlation_threshold: 0.1
    linkage_method: "average"
    distance_threshold: 0.2
    min_group_size: 2
  
  dtw:
    downsample_factor: 3
    linkage_method: "average"
    distance_percentile: 30
    min_group_size: 2